### ISSUE TITLE
Logical modeller design page always refreshes to expanded tree hierarchy after every update

### ISSUE THREAD

**Issue by rodmcd** [davidhay25/clinFHIR#10]

**Comment by davidhay25** [comment]
changed to collapse after edit - though not sure if that is an improvement. Might be better to capture the current state of the tree and restore after editing. Will look at this in due course...

**Comment by rodmcd** [comment]
Totally concur with better to capture current state and restore after editing!

**Comment by davidhay25** [comment]
remembers state of tree before major actions and updates after refresh...
