### ISSUE TITLE
Error when saving logical model with any Concept Map urls entered

### ISSUE THREAD

**Issue by rodmcd** [davidhay25/clinFHIR#25]
![screen shot 2017-05-30 at 7 52 25 am](https://cloud.githubusercontent.com/assets/28239063/26560776/367a6d92-450d-11e7-91a3-dab5ae85b4d3.png)

**Comment by davidhay25** [comment]
There'll be an error tab that appears. Can you do a screen dump of that
one?

Could you try a different browser (in case it's the CORS issue)

**Comment by rodmcd** [comment]
![screen shot 2017-05-30 at 11 50 04 am](https://cloud.githubusercontent.com/assets/28239063/26563940/81ca1f74-452e-11e7-8cd3-faab81d328f3.png)
Is this what you want?? I was able to add concept map url in Safari browser.

**Comment by rodmcd** [comment]
Also able to save in Chrome after clearing browser cache.
