### ISSUE TITLE
Update to FHIR R4

### ISSUE THREAD

**Issue by tkampp** [davidhay25/clinFHIR#39]
Hi,

Is it planned already to update clinFHIR to the recently released FHIR R4 version? 

Thank you,
Thorsten

**Comment by davidhay25** [comment]
Hi Thorsten - yes, it's on the roadmap. Do you have specific requirements?

cheers

**Comment by tkampp** [comment]
Hi David,

Thank you, that's great.

No, we do not have specific requirements yet. We are currently evaluating whether it makes sense to use clinFHIR to assist during specification, quality assurance, and training. As we are moving to FHIR R4, it would be crucial to have that on the roadmap.

All the best,
Thorsten
